### PR TITLE
new registration form

### PR DESCRIPTION
**Pull request by celsoMartins**
pasted image at 2016_02_17 11_27 am

### CODE REVIEW

**Comment by vieiragabriel** [comment]
Translation needs: Choose the payment type
I suggest to insert a new input text/number as:  Experiência com agilidade(anos)

**Comment by celsoMartins** [comment]
image

**Comment by gorequeen** [comment]
My 50 cents from a usability point of view:
- Contact Info should come above professional info. It has more important data (the mandatory fields already make that clear)
- País, Cidade and Estado should appear together and one after the other
- It's not clear for me what Função means, could be renamed to Cargo, I believe it's more common 

Food for thought:
In a future release we could leave only mandatory info in this form and after "Submeter Inscrição" we can redirect the user to another screen saying something like "Now that you are already registered to the conference, why don't you share some more info to help us know you (yada yada)..."
The reason is that filling forms are boring tasks and we don't want people getting annoyed with optional info when they want to quickly finish this task and move on with their life. They can come back later to add more info to their profile if they want to but we shouldn't distract them from the main goal .

**Comment by celsoMartins** [comment]
Thanks for your comments. I agree with your thoughts. We want this change (another form to additional information), but I think that we will have it for the AgileBrazil 2017.

Our form has two columns. So, can we go with this?

image

**Comment by pi-machado** [comment]
Cool! I think it works.

**Comment by celsoMartins** [comment]
@hugocorbucci and others:

What do you think?

image

image

**Pull request merged**
