### PR TITLE
New registration system

### PR DESCRIPTION
**Pull request by celsoMartins**
Work in progress Pull Request. Before the merge we want to do a lot of tests in the staging env.

New UI and UX experience. Fixed backend mistakes. Added some database constraints to have a better data consistency. Also fixed UI of emails.

Some screens

image
image
image
image

**Admin events index:**
image

**Organizer view of the event:**
image
image

**Organizer view of the attendance form**
image

**Admin new event screen**
image

image

image

image

**Email body example**
image

### CODE REVIEW

**Comment by hugocorbucci** [comment]
Few things I'm noticing:

- Recovering password doesn't seem to work. Didn't get an email. And after I asked for the email, I went to a blank page
- Running the migrations doesn't work because of the new methods in user and attendance that rely on the data being in the mysql tables. Let's move the migrations to a separate PR and get them merged so I can run them separately before deploying this change

I'll post more as I find more stuff

**Comment by hugocorbucci** [comment]
New deploy, new findings:

1. After completing a registration for an event, I get redirected to a blank page. I can reload and get data back but the first redirect is blank
2. Uploading images doesn't seem to be working, both for users and for conferences.
3. In the registrations page, the "load info" button to pre-fill data is not working. Like in 
image
4. Many of the text fields don't make much sense (Text field "Escola" in registration, Text field "Logo do evento" in a new event screen)
5. For non-admins, the redirect after the registration is actually a blank AND a 404 on reload.
6. For some reason, I'm not getting any emails. I suspect it is because emails need to be sent from an authorized email and AWS doesn't like that's we're using the "contact" email as the "from". We might need to keep that as a system config.
7. The button to confirm a registration as an admin doesn't update the state of the registration so it looks like it doesn't work but, with a refresh, things are updated. Same for cancel registration.

**Comment by celsoMartins** [comment]
> New deploy, new findings:
> 
> 1. After completing a registration for an event, I get redirected to a blank page. I can reload and get data back but the first redirect is blank
> 2. Uploading images doesn't seem to be working, both for users and for conferences.
> 3. In the registrations page, the "load info" button to pre-fill data is not working. Like in
>    image
> 4. Many of the text fields don't make much sense (Text field "Escola" in registration, Text field "Logo do evento" in a new event screen)
> 5. For non-admins, the redirect after the registration is actually a blank AND a 404 on reload.
> 6. For some reason, I'm not getting any emails. I suspect it is because emails need to be sent from an authorized email and AWS doesn't like that's we're using the "contact" email as the "from". We might need to keep that as a system config.
> 7. The button to confirm a registration as an admin doesn't update the state of the registration so it looks like it doesn't work but, with a refresh, things are updated. Same for cancel registration.

**Comment by celsoMartins** [comment]
@hugocorbucci sobre o 3 eu testei em staging e funfou.. você precisa usar um email válido, que exista no banco, vinculado a um usuário com as informações do form..

**Comment by celsoMartins** [comment]
Confirmação de inscrição local, funfando de primeira, sem tela branca e confirmei que está com problemas em staging. No log aparece rollback no banco, tanto no User (imagem) quanto no Attendance (nova inscrição). Parece que algo oculto está acontecendo no banco e preciso subir um código pra cuspir todos os erros do model (user e attendance) no form.

https://jmp.sh/CxJfeCq

**Pull request merged**
